# Generated by Django 3.0.4 on 2020-03-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('verification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_requirement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('url_ktp_photo', models.CharField(default='url', max_length=300)),
                ('url_self_photo', models.CharField(default='url', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FileRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_file', models.CharField(default='url', max_length=300)),
                ('arrangement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Arrangement')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ServiceRequirements')),
            ],
        ),
        migrations.CreateModel(
            name='DetailRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ServiceRequirements')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Services')),
            ],
        ),
        migrations.AddField(
            model_name='arrangement',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Services'),
        ),
        migrations.AddField(
            model_name='arrangement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
    ]
