# Generated by Django 3.0.4 on 2020-03-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200317_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
