# Generated by Django 3.0.4 on 2020-05-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200321_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
