# Generated by Django 3.0.4 on 2020-05-10 07:48

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200509_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=django_mysql.models.EnumField(choices=[('verified', 'verified'), ('unverified', 'unverified'), ('rejected', 'rejected')], default='unverified'),
        ),
    ]
